import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./_components/navigation/Navbar";
import Footer from "./_components/navigation/Footer";

// font configuration (To be replaced with a better font)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Meta data
export const metadata = {
  title: "Cyber Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen overflow-x-hidden bg-neutral-50`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
